// A real, runnable verification of the updater wiring: the full check ->
// staged download -> Ed25519 signature verification round trip against a local
// fixture HTTP server, then a tampered-manifest rejection check. Uses the real
// `tauri_plugin_updater` crate end to end, nothing reimplemented or mocked at
// the network or signature-verification layer.
//
// This builds a real Tauri app, but on the mock runtime
// (tauri::test::mock_builder / MockRuntime) rather than the real Wry runtime.
// Two Tauri-on-Windows facts force that choice, both deterministic and neither
// specific to any one machine:
//
//   1. Load. tao statically imports comctl32!TaskDialogIndirect, which only
//      the Common-Controls v6 assembly exports. tauri-build embeds the v6
//      application manifest only for bin targets, so a cargo-test binary that
//      links tao at all crashes at process load with STATUS_ENTRYPOINT_NOT_FOUND
//      (0xC0000139). build.rs now embeds that manifest for test and example
//      targets too, which is what lets this test load.
//   2. Run. The real Wry event loop must be created on the main thread, but
//      cargo runs each test on a worker thread, so constructing a real runtime
//      here would panic. MockRuntime has no such requirement.
//
// See docs/adr/0001-tauri-test-binaries-common-controls-manifest.md for the
// full root cause and fix.
//
// What this does and does not prove, stated plainly: it proves the real
// signature-verification code path accepts a correctly-signed artifact and
// rejects a tampered one, and that verified bytes reach the real
// `Update::install` call. It does not, and cannot safely, prove a real NSIS
// installer actually swaps files on disk and relaunches, or that a real Windows
// toast notification renders on screen; both need either a live update server
// or an interactive desktop session. See docs/KNOWN_ISSUES.md and
// src/updater.rs's module doc for the same caveat stated where a reader would
// look for it later.
//
// Fixture material under fixtures/updater/ is committed, pre-generated by
// fixtures/updater/generate.mjs using a throwaway test-only Ed25519 keypair
// that is never written to disk and is never the real release signing key
// documented in release/KEYS.md.

use tauri::test::{mock_builder, mock_context, noop_assets, MockRuntime};
use tauri_plugin_updater::UpdaterExt;

const ARTIFACT: &[u8] = include_bytes!("fixtures/updater/artifact.bin");
const MANIFEST_TEMPLATE: &str = include_str!("fixtures/updater/latest.json");
const TAMPERED_SIGNATURE: &str = include_str!("fixtures/updater/tampered-signature.txt");
const PUBKEY: &str = include_str!("fixtures/updater/pubkey.tauri-config-value.txt");

// The real, committed release updater public key: the exact base64 value that
// ships in ui/src-tauri/tauri.conf.json's plugins.updater.pubkey, read straight
// from the committed release key material so the wrong-key test below cannot
// drift from what the app actually verifies against. This is PUBLIC key material
// (release/KEYS.md); the matching private key never lives in the repo. A
// manifest signed by anything other than this key's private half must be
// refused.
const RELEASE_PUBKEY: &str = include_str!("../../../release/keys/updater_pubkey.tauri-config-value.txt");

// The shipped shell config, included so a test can prove the pubkey the app is
// actually built to trust is the committed release key, not merely some key.
const TAURI_CONF: &str = include_str!("../tauri.conf.json");

struct FixtureServer {
    addr: std::net::SocketAddr,
}

impl FixtureServer {
    /// Spawns a background thread that serves exactly two requests (the
    /// manifest, then the artifact) and returns. Deliberately not joined
    /// anywhere: an earlier version of this bounded the server at more requests
    /// than a single check-and-download round trip actually makes, so
    /// `incoming_requests()` blocked forever on a request that was never
    /// coming, and joining that handle on drop hung the whole process. Two
    /// short-lived, independent fixture servers per run, never joined, and left
    /// to be reclaimed when the process exits, sidesteps that class of bug
    /// entirely instead of just picking a request count and hoping nothing ever
    /// needs a retry.
    ///
    /// Serves `artifact_bytes` for `/artifact.bin`, so a test can serve payload
    /// bytes that differ from the ones the manifest signature was computed over
    /// (the tampered-artifact case). Most tests want the committed fixture
    /// artifact and call [`FixtureServer::start`], which forwards `ARTIFACT`.
    fn start_serving(manifest_body: String, artifact_bytes: Vec<u8>) -> Self {
        let server = tiny_http::Server::http("127.0.0.1:0").expect("failed to bind the fixture server");
        let addr = server
            .server_addr()
            .to_ip()
            .expect("fixture server should be bound to an IP address");
        let manifest_body = manifest_body.replace("{{BASE_URL}}", &format!("http://{addr}"));

        std::thread::spawn(move || {
            for request in server.incoming_requests().take(2) {
                let url = request.url().to_string();
                let outcome = if url == "/latest.json" {
                    let header = tiny_http::Header::from_bytes(&b"Content-Type"[..], &b"application/json"[..]).unwrap();
                    request.respond(tiny_http::Response::from_string(manifest_body.clone()).with_header(header))
                } else if url == "/artifact.bin" {
                    let header =
                        tiny_http::Header::from_bytes(&b"Content-Type"[..], &b"application/octet-stream"[..]).unwrap();
                    request.respond(tiny_http::Response::from_data(artifact_bytes.clone()).with_header(header))
                } else {
                    request.respond(tiny_http::Response::from_string("not found").with_status_code(404))
                };
                let _ = outcome;
            }
        });

        Self { addr }
    }

    /// Serves the committed fixture artifact for `/artifact.bin`. The happy-path
    /// and tampered-signature tests use this; only the tampered-artifact test
    /// needs [`FixtureServer::start_serving`] with different bytes.
    fn start(manifest_body: String) -> Self {
        Self::start_serving(manifest_body, ARTIFACT.to_vec())
    }

    fn manifest_url(&self) -> url::Url {
        format!("http://{}/latest.json", self.addr)
            .parse()
            .expect("constructed URL should always be valid")
    }
}

/// Builds a real Tauri app on the mock runtime with only the updater plugin
/// registered.
///
/// The updater plugin deserializes its `plugins.updater` config at plugin init,
/// before its own setup runs, and that config requires a `pubkey` field. A mock
/// context has no such config, so inject a minimal valid one here; the actual
/// pubkey and endpoints each check runs against are overridden per check via
/// `updater_builder()` below, so this injected value is only there to satisfy
/// config deserialization.
fn build_app() -> tauri::App<MockRuntime> {
    let mut context = mock_context(noop_assets());
    context.config_mut().plugins.0.insert(
        "updater".to_string(),
        serde_json::json!({ "pubkey": PUBKEY.trim(), "endpoints": [] }),
    );
    mock_builder()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .build(context)
        .expect("failed to build the mock app")
}

fn manifest_signature(manifest_json: &str) -> String {
    let value: serde_json::Value = serde_json::from_str(manifest_json).expect("fixture manifest must be valid JSON");
    value["signature"]
        .as_str()
        .expect("fixture manifest must have a string signature field")
        .to_string()
}

#[tokio::test]
async fn check_download_and_verify_against_fixture_server() {
    let server = FixtureServer::start(MANIFEST_TEMPLATE.to_string());
    let app = build_app();

    let updater = app
        .handle()
        .updater_builder()
        .endpoints(vec![server.manifest_url()])
        .expect("fixture endpoint should be a valid (http, allowed in debug builds) URL")
        .pubkey(PUBKEY.trim())
        .build()
        .expect("failed to build the updater against the fixture config");

    let update = updater
        .check()
        .await
        .expect("check() should succeed against a well-formed, correctly-signed fixture manifest")
        .expect("the fixture manifest's version (9.9.9) is newer than the app's, so an update should be reported");
    assert_eq!(update.version, "9.9.9");

    let bytes = update
        .download(|_chunk_len, _total_len| {}, || {})
        .await
        .expect("download() verifies the Ed25519 signature internally; a correctly-signed artifact must pass");
    assert_eq!(
        bytes, ARTIFACT,
        "the bytes handed back after verification should be exactly the signed fixture artifact"
    );

    // The swap step. `install` here is the real, unmodified plugin method, not
    // a stand-in, handed the exact bytes that just passed verification above.
    // The fixture artifact is deliberately not a real Windows executable, so
    // `install` fails fast at its own "is this actually an installer" sniff
    // (checked before anything is ever shelled out to) rather than launching a
    // process, proving the real call is reachable and wired to
    // genuinely-verified bytes without needing to run a real installer to prove
    // it.
    let install_result = update.install(bytes);
    match &install_result {
        Err(tauri_plugin_updater::Error::InvalidUpdaterFormat) => {}
        other => panic!(
            "expected install() to reach its real format-sniff step and reject the non-installer fixture bytes with InvalidUpdaterFormat, got: {other:?}"
        ),
    }
}

#[tokio::test]
async fn tampered_manifest_signature_is_rejected() {
    let original_signature = manifest_signature(MANIFEST_TEMPLATE);
    let tampered_manifest = MANIFEST_TEMPLATE.replacen(&original_signature, TAMPERED_SIGNATURE.trim(), 1);
    assert_ne!(
        tampered_manifest, MANIFEST_TEMPLATE,
        "sanity check: the tampering substitution must actually change the manifest text"
    );

    let server = FixtureServer::start(tampered_manifest);
    let app = build_app();

    let updater = app
        .handle()
        .updater_builder()
        .endpoints(vec![server.manifest_url()])
        .expect("fixture endpoint should be a valid URL")
        .pubkey(PUBKEY.trim())
        .build()
        .expect("failed to build the updater against the fixture config");

    // check() only parses the manifest JSON and compares version numbers; it
    // does not touch the signature at all, so a tampered signature field alone
    // does not fail it. The rejection has to happen at download(), which is
    // exactly what makes it meaningful: a manifest served over a compromised or
    // MITM'd channel is still cryptographically checked before any bytes are
    // trusted, not just structurally validated.
    let update = updater
        .check()
        .await
        .expect("check() does not verify signatures, so a tampered signature field alone must not fail it")
        .expect("the fixture manifest's version is still newer, so an update should still be reported");

    let result = update.download(|_chunk_len, _total_len| {}, || {}).await;
    match &result {
        Err(tauri_plugin_updater::Error::Minisign(_) | tauri_plugin_updater::Error::Base64(_)) => {}
        Ok(_) => panic!("a manifest with a tampered signature field must be rejected at download/verify time, not accepted"),
        Err(other) => panic!("expected a signature-verification error (Minisign or Base64), got: {other:?}"),
    }
}

#[tokio::test]
async fn manifest_signed_with_wrong_key_is_rejected() {
    // Same well-formed, correctly-signed fixture manifest as the happy path, but
    // this updater is configured with the REAL committed release pubkey
    // (RELEASE_PUBKEY) instead of the fixture's own key. The fixture artifact was
    // signed by a throwaway key whose key id differs from the release key's, so
    // this is exactly the "signed with the wrong key" case: a manifest that is
    // internally consistent and validly signed, just not by the key this build
    // trusts. It must be refused at verify time, not accepted. Concretely,
    // minisign-verify rejects it at its key-id check (self.key_id !=
    // signature.key_id) before it would even look at the signature bytes, and
    // tauri_plugin_updater surfaces that as Error::Minisign.
    let server = FixtureServer::start(MANIFEST_TEMPLATE.to_string());
    let app = build_app();

    let updater = app
        .handle()
        .updater_builder()
        .endpoints(vec![server.manifest_url()])
        .expect("fixture endpoint should be a valid URL")
        .pubkey(RELEASE_PUBKEY.trim())
        .build()
        .expect("failed to build the updater against the real release pubkey");

    // check() does not verify signatures (see the tampered-manifest test), so a
    // wrong-key manifest still passes the structural version check; the rejection
    // has to happen at download/verify.
    let update = updater
        .check()
        .await
        .expect("check() does not verify signatures, so a wrong-key manifest still checks out structurally")
        .expect("the fixture manifest's version is newer, so an update should still be reported");

    let result = update.download(|_chunk_len, _total_len| {}, || {}).await;
    match &result {
        Err(tauri_plugin_updater::Error::Minisign(_)) => {}
        Ok(_) => panic!(
            "a manifest signed by any key other than the configured release key must be rejected at verify time, not accepted"
        ),
        Err(other) => panic!("expected a Minisign key-mismatch verification error, got: {other:?}"),
    }
}

#[tokio::test]
async fn tampered_artifact_bytes_are_rejected() {
    // The manifest and its signature are the genuine, correctly-keyed fixture
    // pair (verified here against the fixture's own pubkey), but the bytes served
    // for the artifact are not the ones that were signed: one byte is flipped.
    // This is the payload-swap attack, distinct from the tampered-signature test:
    // there the signature was altered and the artifact left intact; here the
    // signature is intact and correctly keyed, and the artifact is altered. The
    // key-id check therefore passes and the Ed25519 signature check over the
    // swapped bytes fails, so neither the signature nor the signed bytes can be
    // changed independently and still be trusted.
    let mut tampered_artifact = ARTIFACT.to_vec();
    tampered_artifact[0] ^= 0x01;
    assert_ne!(
        tampered_artifact.as_slice(),
        ARTIFACT,
        "sanity check: the flipped-byte artifact must actually differ from the signed one"
    );

    let server = FixtureServer::start_serving(MANIFEST_TEMPLATE.to_string(), tampered_artifact);
    let app = build_app();

    let updater = app
        .handle()
        .updater_builder()
        .endpoints(vec![server.manifest_url()])
        .expect("fixture endpoint should be a valid URL")
        .pubkey(PUBKEY.trim())
        .build()
        .expect("failed to build the updater against the fixture config");

    // check() only reads the manifest, which is untouched, so it still succeeds;
    // download() fetches the swapped artifact bytes and verifies the signature
    // over them, which must fail.
    let update = updater
        .check()
        .await
        .expect("check() only reads the manifest, which is untouched here, so it must still succeed")
        .expect("the fixture manifest's version is newer, so an update should still be reported");

    let result = update.download(|_chunk_len, _total_len| {}, || {}).await;
    match &result {
        Err(tauri_plugin_updater::Error::Minisign(_)) => {}
        Ok(_) => panic!(
            "an artifact whose bytes differ from the signed ones must be rejected at verify time, not accepted"
        ),
        Err(other) => panic!("expected a Minisign signature-verification error over the swapped bytes, got: {other:?}"),
    }
}

#[test]
fn shipped_config_pubkey_matches_committed_release_key() {
    // Ties the wrong-key test to reality: the pubkey that test trusts
    // (RELEASE_PUBKEY, read from release/keys/) is byte-for-byte the pubkey the
    // app actually ships in tauri.conf.json's plugins.updater.pubkey. Without
    // this, "rejected because signed with the wrong key" would only hold against
    // some key; with it, it holds against the exact key this build verifies
    // against. No network: this is a pure config invariant.
    let config: serde_json::Value =
        serde_json::from_str(TAURI_CONF).expect("tauri.conf.json must be valid JSON");
    let config_pubkey = config["plugins"]["updater"]["pubkey"]
        .as_str()
        .expect("tauri.conf.json must set plugins.updater.pubkey as a string");
    assert_eq!(
        config_pubkey,
        RELEASE_PUBKEY.trim(),
        "the pubkey shipped in tauri.conf.json must be the committed release key in release/keys/updater_pubkey.tauri-config-value.txt"
    );
}
